name: Release (from CHANGELOG)

on:
  push:
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version and changelog section
        id: extract
        shell: bash
        run: |
          set -euo pipefail
          TAG_NAME="${GITHUB_REF_NAME}"
          VERSION="${TAG_NAME#v}"

          awk -v ver="## \\["VERSION"\\]" '
            BEGIN{p=0}
            $0 ~ "^" ver {p=1; print; next}
            /^##\s*\[?[0-9]+\.[0-9]+\.[0-9]+\]?/ && p==1 {exit}
            p==1 {print}
          ' CHANGELOG.md > RELEASE_BODY.md || true

          if [ ! -s RELEASE_BODY.md ]; then
            awk -v ver="## "VERSION" " '
              BEGIN{p=0}
              $0 ~ "^" ver {p=1; print; next}
              /^##\s*\[?[0-9]+\.[0-9]+\.[0-9]+\]?/ && p==1 {exit}
              p==1 {print}
            ' CHANGELOG.md > RELEASE_BODY.md || true
          fi

          echo "----- RELEASE BODY -----"
          cat RELEASE_BODY.md || true
          echo "------------------------"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: RELEASE_BODY.md
          draft: false
          prerelease: false
