name: require-changelog
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changelog:
    # ⬇️ Skip für release-please PRs / Bot
    if: |
      github.actor != 'release-please[bot]' &&
      github.actor != 'github-actions[bot]' &&
      !startsWith(github.head_ref, 'release-please--') &&
      !contains(github.event.pull_request.title, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # wichtig, sonst exit code 128 bei git diff
      - name: Fail if CHANGELOG.md not modified
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q '^CHANGELOG\.md$'; then
            echo "Changelog updated ✅"
          else
            echo "Please update CHANGELOG.md ❌"
            exit 1
          fi
