name: semantic-pr

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]

permissions:
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # ✅ ONE TYPE PER LINE (no commas!)
          types: |
            feat
            fix
            docs
            chore
            refactor
            perf
            test
            build
            ci
            revert

          # No scope required => 'chore: …' or 'chore(main): …' both OK
          requireScope: false

          # Optionally skip the check on certain PRs
          ignoreLabels: |
            autorelease: pending
            skip-semantic-check

